### ISSUE TITLE
甲骨文AMD免费鸡一更新内核就重启

### ISSUE THREAD

**Issue by lengxii** [kkkyg/CFwarp#1]
更新系统内核到官方源最新版本！注意，别手滑哦！
 1. Centos7 
 2. Centos8 
 3. Ubuntu20 
 4. Debain10 
 0. 退出脚本 

请输入数字:1
Loaded plugins: fastestmirror, langpacks
elrepo-release-7.el7.elrepo.noarch.rpm                                        | 8.6 kB  00:00:00     
Examining /var/tmp/yum-root-bPk76f/elrepo-release-7.el7.elrepo.noarch.rpm: elrepo-release-7.0-5.el7.elrepo.noarch
/var/tmp/yum-root-bPk76f/elrepo-release-7.el7.elrepo.noarch.rpm: does not update installed package.
Error: Nothing to do
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.shastacoe.net
 * elrepo: ftp.osuosl.org
 * elrepo-kernel: ftp.osuosl.org
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: sjc.edge.kernel.org
 * updates: repo1.sea.innoscale.net
Nothing to do
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.3.13-1.el7.elrepo.x86_64
Found initrd image: /boot/initramfs-5.3.13-1.el7.elrepo.x86_64.img
Found linux image: /boot/vmlinuz-3.10.0-1160.42.2.el7.x86_64
Found initrd image: /boot/initramfs-3.10.0-1160.42.2.el7.x86_64.img
Found linux image: /boot/vmlinuz-3.10.0-1160.36.2.el7.x86_64
Found initrd image: /boot/initramfs-3.10.0-1160.36.2.el7.x86_64.img
Found linux image: /boot/vmlinuz-3.10.0-1160.el7.x86_64
Found initrd image: /boot/initramfs-3.10.0-1160.el7.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-3dbc3e803ba5481dbb063eb06a7ca4bc
Found initrd image: /boot/initramfs-0-rescue-3dbc3e803ba5481dbb063eb06a7ca4bc.img
Found linux image: /boot/vmlinuz-0-rescue-a50dc2bf11d04afb85f66e3b3639c796
Found initrd image: /boot/initramfs-0-rescue-a50dc2bf11d04afb85f66e3b3639c796.img
done

Connection closed by foreign host.

**Comment by kkkyg** [comment]
纯净系统下，注意7与8别选错！

**Comment by kkkyg** [comment]
试下新脚本，不用更新内核。

**Comment by kkkyg** [comment]
我刚试试了下,没问题。。
