### ISSUE TITLE
重启后自动刷新warp的IP？

### ISSUE THREAD

**Issue by crosspacific** [kkkyg/CFwarp#10]
重启后自动刷新warp的IP，这个功能能不能改成可选的？有时候好不容易刷到一个解锁Netflix的节点，但是一关机和重启就没了。😂

**Comment by kkkyg** [comment]
已去除这个功能！但重启vps后还是会刷新！这个无法改变！除非走socks5的warp！！改天脚本会大更新！！

**Comment by crosspacific** [comment]
OK。
