### ISSUE TITLE
[BUG]在kurun云 速度异常

### ISSUE THREAD

**Issue by taostart** [kkkyg/CFwarp#12]
VPS系统信息如下：
 原生真IP特征: Only纯IPV4的VPS
 操作系统名称: Debian GNU/Linux 10
 系统内核版本: 5.15.6
 CPU架构名称 : x86_64
 虚拟架构类型: kvm
MTU最佳网络吞吐量值= 1370

root@s:~# speedtest 

   Speedtest by Ookla

     Server: Airlink Internet Inc - Los Angeles, CA (id = 33893)
        ISP: Cloudflare Warp
    Latency:     2.08 ms   (207.08 ms jitter)
   Download:     0.24 Mbps [===|                ] 17%

**Comment by kkkyg** [comment]
实际使用也是这速度吗？

**Comment by taostart** [comment]
> 实际使用也是这速度吗？

当然，实际使用也是这个速度，我怀疑和mtu有关系

**Comment by kkkyg** [comment]
> > 实际使用也是这速度吗？
> 
> 当然，实际使用也是这个速度，我怀疑和mtu有关系

Mtu默认1280，现在自动设为1370了！当然你可以进配置文件自己改！但我觉得效果也不会有很大改变！
