### ISSUE TITLE
Warp+不起作用？

### ISSUE THREAD

**Issue by asterriya** [kkkyg/CFwarp#14]
我选择了7号选项，使双堆栈Cloudflare warp。另外，我打开了warp+，但它根本不占用GB数据。我使用的是我的智能手机的许可证ID。如何解决这个问题，我需要做什么才能使使用warp+？

**Comment by kkkyg** [comment]
After pasting the ID, press Enter QUIDKLY!!!

**Comment by asterriya** [comment]
@kkkyg 是的，我通过智能手机上的许可证ID激活了它。所以它现在显示我有11GB。但数据完全不计。似乎warp+不工作了。但我的IP改变了。只是不通过warp+。如何解决这个问题？

**Comment by asterriya** [comment]
忘了说，我使用的是SS+gost（WSS+CDN打开了）。

**Comment by asterriya** [comment]
找到了解决方案，我是这样做的。

1) 需要升级到最新的内核。我使用的是5.18的Zen内核。之后，重新启动系统。
2) 需要在安卓上安装新的1.1.1.1应用程序，并复制许可证ID+技术ID。
3) 首先运行配额脚本。之后才开始使用你需要的东西。我选择双堆栈选项。
4) 应用 
systemctl stop wg-quick@wgcf && systemctl disable wg-quick@wgcf && systemctl status wg-quick@wgcf
systemctl start wg-quick@wgcf && systemctl enable wg-quick@wgcf && systemctl status wg-quick@wgcf
5) 应用 
resolvconf --enable-updates
resolvconf -u
nano /etc/resolv.conf

之后，我检查了智能手机上的GB数据，它开始减少，因为它必须这样。

通过www.DeepL.com/Translator（免费版）翻译

**Comment by kkkyg** [comment]
> 找到了解决方案，我是这样做的。
> 
> 1. 需要升级到最新的内核。我使用的是5.18的Zen内核。之后，重新启动系统。
> 2. 需要在安卓上安装新的1.1.1.1应用程序，并复制许可证ID+技术ID。
> 3. 首先运行配额脚本。之后才开始使用你需要的东西。我选择双堆栈选项。
> 
> 之后，我检查了智能手机上的GB数据，它开始减少，因为它必须这样。
> 
> 注意：也许这很重要，我不知道。但我在warp+内开始连接我的应用程序，以使它首先处于活动状态。

看来，内核模块的WARP问题的确很多，下回就剔除掉它。

**Comment by asterriya** [comment]
另外，我听说团队的Cloudflare有warp或warp+，但不确定。

这是我发现的。
https://pkg.cloudflareclient.com/install
https://pkg.cloudflareclient.com/packages/cloudflare-warp
https://developers.cloudflare.com/warp-client/get-started/linux
https://developers.cloudflare.com/warp-client/
