### ISSUE TITLE
Warp+的VLESS配置

### ISSUE THREAD

**Issue by asterriya** [kkkyg/CFwarp#15]
我使用的是双堆栈Warp+，这是我对v2ray的配置（ws+cdn+vless），那么如何配置呢？我想主要看到Ipv4，因为Warp+。

    "outbounds": [
        {
            "tag":"IPv4_out",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "AsIs"
            }
        },        
        {
            "tag": "blocked",
            "protocol": "blackhole",
            "settings": {}
        },
        
        
        {
            "tag":"IPv6_out",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv6" 
            }
        },
        {
            "tag": "WARP_out",
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1",
                        "port": 40000
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"
            }
        }
    ]
}

**Comment by kkkyg** [comment]
你先试试这个，我不确定在你的环境下能用！！！
"outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1",
                        "port": 40000
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"
                },
            "tag": "warp"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
