### ISSUE TITLE
与x-ui面板无法兼容，开启后xui面板无法联网

### ISSUE THREAD

**Issue by Sevenzhi** [kkkyg/CFwarp#16]

**Comment by kkkyg** [comment]
实测并不冲突哦，。。XUI面版用本地IP解析的域名或者本地IP访问
不要把WARP的IP当回事，WARP的IP没实际用处！

**Comment by Sevenzhi** [comment]
> 实测并不冲突哦，。。XUI面版用本地IP解析的域名或者本地IP访问
> 
> 不要把WARP的IP当回事，WARP的IP没实际用处！

是xui 创建的节点无法联网

**Comment by kkkyg** [comment]
> > 实测并不冲突哦，。。XUI面版用本地IP解析的域名或者本地IP访问
> > 不要把WARP的IP当回事，WARP的IP没实际用处！
> 
> 是xui 创建的节点无法联网

我试了没问题的！

**Comment by kkkyg** [comment]
> > 实测并不冲突哦，。。XUI面版用本地IP解析的域名或者本地IP访问
> > 不要把WARP的IP当回事，WARP的IP没实际用处！
> 
> 是xui 创建的节点无法联网

重启下x-ui
