### ISSUE TITLE
debian11获取ip失败

### ISSUE THREAD

**Issue by yuanweize** [kkkyg/CFwarp#17]
![image](https://user-images.githubusercontent.com/30067203/148077383-798b7da8-70ca-48d5-a52c-5e58b29b92d8.png)![image](https://user-images.githubusercontent.com/30067203/148077395-57045e75-8e75-4bf8-b998-1a361ac4ffff.png)如图

**Comment by kkkyg** [comment]
用原生内核，卸载你的bbrplus先！再执行脚本！

**Comment by yuanweize** [comment]
> 用原生内核，卸载你的bbrplus先！再执行脚本！

问题解决了,具体过程[https://github.com/fscarmen/warp/issues/54#issuecomment-1005352313](url)
