### ISSUE TITLE
德鸡DiG9重装系统后无连接

### ISSUE THREAD

**Issue by love2wind** [kkkyg/CFwarp#19]
各种方法都试过了，就是无法连接。
新装Debian 10后就无法更新，warp就更别说了。不知道咋回事。

**Comment by kkkyg** [comment]
先执行
echo -e "search blue.kundencontroller.de\noptions rotate\nnameserver 2a02:180:6:5::1c\nnameserver 2a02:180:6:5::4\nnameserver 2a02:180:6:5::1e\nnameserver 2a02:180:6:5::1d" > /etc/resolv.conf

再运行脚本试下

**Comment by love2wind** [comment]
> 先执行 echo -e "search blue.kundencontroller.de\noptions rotate\nnameserver 2a02:180:6:5::1c\nnameserver 2a02:180:6:5::4\nnameserver 2a02:180:6:5::1e\nnameserver 2a02:180:6:5::1d" > /etc/resolv.conf
> 
> 再运行脚本试下

试过了，重装了两次系统都是一样。

**Comment by kkkyg** [comment]
更新好了

**Comment by love2wind** [comment]
> 更新好了

![image](https://user-images.githubusercontent.com/11996852/148509487-beed0f18-a8b2-4963-96ae-1261bd930967.png)

还是一样的，先执行了 echo -e "search blue.kundencontroller.de\noptions rotate\nnameserver 2a02:180:6:5::1c\nnameserver 2a02:180:6:5::4\nnameserver 2a02:180:6:5::1e\nnameserver 2a02:180:6:5::1d" > /etc/resolv.conf

**Comment by love2wind** [comment]
感觉是整个主机没有网络
