### ISSUE TITLE
ipv6 vps安装双栈 (IPv4/​IPv6)后就连不上

### ISSUE THREAD

**Issue by delphinuz** [kkkyg/CFwarp#20]
安装ipv4 wrap很正常，但如果改为双栈 (IPv4/​IPv6)，立马完全都连不上了。

很好奇对ipv6 vps，为何一加上ipv6为双栈就无法正常连接？

**Comment by kkkyg** [comment]
连不上是指登不上ssh？
什么vps？什么系统？

**Comment by delphinuz** [comment]
EUServ，只有ipv6。

用一键安装wrap ipv4就没问题，但一选择双栈，安装完就失连，需要整个系统重新安装才行。

**Comment by kkkyg** [comment]
什么系统？

**Comment by kkkyg** [comment]
> EUServ，只有ipv6。
> 
> 用一键安装wrap ipv4就没问题，但一选择双栈，安装完就失连，需要整个系统重新安装才行。

什么系统？

**Comment by delphinuz** [comment]
debian11。

**Comment by yanwo592** [comment]
> debian11。

我用的以前的脚本可以双栈。没更新之前我的Euserv的直接不能获取 后来找的以前的

**Comment by kkkyg** [comment]
> > debian11。
> 
> 我用的以前的脚本可以双栈。没更新之前我的Euserv的直接不能获取 后来找的以前的

我试了下！没问题哦！

**Comment by delphinuz** [comment]
谢谢各位，我试一下。
