### ISSUE TITLE
screen刷ip任务并未创建

### ISSUE THREAD

**Issue by jasonding121205** [kkkyg/CFwarp#21]
是否和ip已经解锁nf有关？screen -ls命令显示并未新建后台任务

**Comment by kkkyg** [comment]
你看看有没有：选择进入screen管理，选择2，应该会有aw字样，输入aw查看执行过程

**Comment by jasonding121205** [comment]
screen显示无执行内容，也没有aw字样，两台vps都试过了，需要手动创建screen任务执行NFC脚本。只是小瑕疵，感谢up主分享脚本

**Comment by kkkyg** [comment]
> screen显示无执行内容，也没有aw字样，两台vps都试过了，需要手动创建screen任务执行NFC脚本。只是小瑕疵，感谢up主分享脚本

有空我再测试修下。感谢反馈

**Comment by kkkyg** [comment]
脚本已更新 ，已修复此问题

**Comment by jasonding121205** [comment]
实测已修复，感谢大佬

**Comment by jasonding121205** [comment]
但是还有个小问题，vps重启后刷ip任务并未自动创建

**Comment by kkkyg** [comment]
> 但是还有个小问题，vps重启后刷ip任务并未自动创建

再试试看
