### ISSUE TITLE
请问是否有定时检查NF失效？

### ISSUE THREAD

**Issue by lucas-su-dev** [kkkyg/CFwarp#22]
看了看7离线自动刷NF好像是重启以后才启动脚本。
但本人使用经验，一般香港，台湾，新加坡，日本的可用ip较少，而且经常1天左右就自动切换成非NF ip了。
所以基本每天我都手动登录VPS，前台刷新一遍。

能否有个功能设置每个多少小时检查一下，比如2小时检查是否该IP已经不支持NF了。
并且10次还是有点儿少。香港的一般需要刷30次才能找到NF ip

**Comment by kkkyg** [comment]
目前离线后台刷nf启动不了是有个bug，明天我更新下！
离线刷现在默认30秒自动刷！我调整下让大家自定义

**Comment by kkkyg** [comment]
已修复离线无法执行刷奈飞IP问题。。自定义时间段分为奈飞IP成本后检测时间段，与非奈飞IP检测时间段。。明天更新

**Comment by lucas-su-dev** [comment]
VPS操作系统: Debian GNU/Linux 11 (bullseye)  内核版本: 4.14.129  CPU架构 : AMD64  虚拟化类型: kvm  TCP算法: bbrplus

uk
8.42.172.143 不支持
8.26.180.45	支持
hk
8.21.11.195 不支持
8.21.11.203 支持
au
8.39.18.119 支持
8.39.18.6 支持
8.39.18.208 支持

我试着用最新的7-2-1安装并启动screen，的确是在后台不停的刷新ip，大概确实是30秒变一次。但是不管支不支持NF，他都会继续刷新ip。我以为刷到支持的NF时候他就会停下来，结果一直不停，短短几分钟变了十几次ip，有时候支持的又跳过了。赶紧把screen卸载了。

系统是debian 10和11都测过不行，是不是因为debian的问题导致判断nf失败

**Comment by lucas-su-dev** [comment]
还有个建议就是就是能不能指定cf的地区，自动判断真的有时候有问题。韩国甲骨文用这个脚本，cf到hk去了，本来首尔有cf节点的。
能不能问一下指定国家，比如kr表示韩国。这样就不会自动判断出问题

**Comment by kkkyg** [comment]
> 

刷ip是重启机制！如果是双栈warp！目前判断只要v4或v6一个不支持nf，就都会刷新！选单栈2为好

**Comment by kkkyg** [comment]
> 还有个建议就是就是能不能指定cf的地区，自动判断真的有时候有问题。韩国甲骨文用这个脚本，cf到hk去了，本来首尔有cf节点的。 能不能问一下指定国家，比如kr表示韩国。这样就不会自动判断出问题

国家选择很重要？目前默认只要支持nf就好

**Comment by lucas-su-dev** [comment]
噢，原来不停刷新是双栈导致的。那我等一等下一版嘿~虽然ipv6没什么用。

ipv4不支持NF能不能单独刷新ipv4呢，ipv6不支持也无所谓，毕竟访问NF还是用的ipv4

选地区这个对于自动判断错误的就很有必要~比如这个韩国甲骨文被判断到hk地区，这样流量从本地到韩国以后还要去一趟香港，再回韩国，再回来，延迟高得太多没法用。虽然韩国甲骨文本身就支持NF。但是他原生IP被很多网站判断地区错误，北美的，香港的都有。还想要套一个CF。这样地区就统一成韩国了。

**Comment by lucas-su-dev** [comment]
emm~再问一下。我用gcp 新的debian 11未改动任何设置测试了一下脚本。有两个问题。
1.只开ipv4，开启后台离线刷ip，发现ip仍然一直在刷，刷到可nf的也不停。
开ipv4和ipv6双栈的，好像还是两个ip都在不停刷，也没有停，而且也不是只刷新ipv4.

如果能真的刷出nf，我不用ipv6也没影响，但是我这儿ipv4也不行。

2.更奇怪的是。。我用脚本选4清除screen所有任务以后。再开启离线脚本，提示是添加了aw任务但是却没有。我用的root用户。这个时候我后动bash 运行刷新ip的脚本，ip都不变，我看了脚本也不知道哪儿出问题了= =卸载了screen再安装也不行。

不知道是debian的问题还是我这儿个例。

**Comment by lucas-su-dev** [comment]
实测了一下，确实无论支不支持，都还是在不停刷新
以下是ip变化的情况

8.21.11.215（不支持）

8.39.127.8（不支持）

8.21.11.177（不支持）

8.21.11.191(支持奈菲)
2a09:bac0:23::815:bbf(不支持奈菲)

8.21.11.227（支持奈菲）
2a09:bac0:23::815:be3(不支持奈菲)

8.21.11.159（不支持）

8.21.11.191已经支持了，脚本还在刷新，而且每次刷新都是ipv6一起刷新的

**Comment by kkkyg** [comment]
> 

用原脚本先卸载！刚更新过了

**Comment by kkkyg** [comment]
明天更新区域自定义设定

**Comment by lucas-su-dev** [comment]
终于用上了！实测没问题。
稳定一天了。所有节点均解锁NF。
但是使用最新的脚本，韩国甲骨文。
自动识别的CF地区是日本

安装完双栈以后得到的地区ipv4 ipv6都是日本，然后我选自动刷新刷新，输入地区代码KR
自动刷ip没起作用，不停地刷新，还是日本的节点。没有得到韩国的CF。首尔应该有CF节点吧，https://www.cloudflare.com/network/ 
 这儿看到首尔有个点。
另外就是日本好像是大阪和东京2个节点，美国也有很多节点，LA，NY之类的，只写国家，没有测过一个国家多节点的会用哪个节点~

非常感谢~
从最开始没法刷新，到多次刷新，到双栈，到换地区，都修复了，实在不容易

**Comment by kkkyg** [comment]
> 

刷新地区是否成功真的是机率！！不是你填韩国就只往韩国那刷的哦！
