### ISSUE TITLE
beta2脚本有问题，会清空我的vps的dns

### ISSUE THREAD

**Issue by 759071793** [kkkyg/CFwarp#23]
beta2脚本有问题，会清空我的vps的dns

**Comment by kkkyg** [comment]
> beta2脚本有问题，会清空我的vps的dns

Dns就为空了吗？

**Comment by 759071793** [comment]
是的勇哥，beta1美誉问题，我用三个vps测试，都是centos7

**Comment by 759071793** [comment]
执行脚本安装warp直接退出脚本，然后dns就被清空了

**Comment by kkkyg** [comment]
> 执行脚本安装warp会自动退出脚本，然后dns就被清空了

什么鸡呀？

**Comment by 759071793** [comment]
> > 执行脚本安装warp会自动退出脚本，然后dns就被清空了
> 
> 什么鸡呀？

Racknerd、Vultr、Maxkvm、Hostodo

**Comment by kkkyg** [comment]
> > > 执行脚本安装warp会自动退出脚本，然后dns就被清空了
> > 
> > 
> > 什么鸡呀？
> 
> Racknerd、Vultr、Maxkvm、Hostodo

这么多！都半途退出？你试下干净的系统

**Comment by 759071793** [comment]
Maxkvm我是发现问题重新装的centos7，然后只要用beta2版本，选择234选项就会半途直接退出然后dns被清空了，我回到beta1一切正常，就是反馈下问题，我喜欢用你的这个脚本，因为可以单独选择开单栈

**Comment by kkkyg** [comment]
> Maxkvm我是发现问题重新装的centos7，然后只要用beta2版本，选择234选项就会半途直接退出然后dns被清空了，我回到beta1一切正常，就是反馈下问题，我喜欢用你的这个脚本，因为可以单独选择开单栈

Maxkvm支持自定义改dns吗？

**Comment by 759071793** [comment]
> > Maxkvm我是发现问题重新装的centos7，然后只要用beta2版本，选择234选项就会半途直接退出然后dns被清空了，我回到beta1一切正常，就是反馈下问题，我喜欢用你的这个脚本，因为可以单独选择开单栈
> 
> Maxkvm支持自定义改dns吗？ 我一直觉的是个意外！哈哈！再试试看？

我刚重新测了勇哥。。还是会直接清空 /etc/resolv.conf 文件。。对了，我是替换了新版bbrplus加速内核的，但是我用beta1版本没有问题呀，用beta2就有问题。。奇怪

**Comment by 759071793** [comment]
> > Maxkvm我是发现问题重新装的centos7，然后只要用beta2版本，选择234选项就会半途直接退出然后dns被清空了，我回到beta1一切正常，就是反馈下问题，我喜欢用你的这个脚本，因为可以单独选择开单栈
> 
> Maxkvm支持自定义改dns吗？ 我一直觉的是个意外！哈哈！再试试看？

而且我这次使用的racknerd的vps，不过系统还是centos7

**Comment by 759071793** [comment]
这个[wget -N --no-check-certificate "https://github.000060000.xyz/tcpx.sh" && chmod +x tcpx.sh && ./tcpx.sh](tcpx.sh)脚本，选择的5
 VPS操作系统: CentOS Linux 7 (Core)  内核版本: 5.10.89  CPU架构 : AMD64  虚拟化类型: kvm  TCP算法: bbrplus

**Comment by kkkyg** [comment]
> 这个`wget -N --no-check-certificate "https://github.000060000.xyz/tcpx.sh" && chmod +x tcpx.sh && ./tcpx.sh`脚本，选择的5 VPS操作系统: CentOS Linux 7 (Core) 内核版本: 5.10.89 CPU架构 : AMD64 虚拟化类型: kvm TCP算法: bbrplus

用自带原生内核试下先

**Comment by 759071793** [comment]
原来机器上有文件不好动，我新开了一个vultr的机器，替换了内核 beta2 都没有问题了，但是别的以前的机器，只能用beta1，用beta2就不行，晕死了，勇哥，能帮我看看不。

**Comment by 759071793** [comment]
`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 WARP-WGCF/SOCKS5安装脚本：2022.1.15更新 Beta 2 版本
 详细说明 https://github.com/kkkyg/CFwarp  YouTube频道：甬哥侃侃侃
 切记：进入脚本快捷方式 bash CFwarp.sh 
 ==================一、VPS相关调整选择（更新中）==========================================
  1. 一键ROOT脚本、开启甲骨文端口规则、开启BBR加速、更新5.6以上内核、设置VPS本地IP优先级 
 =================二、WARP功能选择（更新中）=============================================
 选项（2、3、4）为安装WARP三个配置方案，可随意切换安装。选项（5）与选项（2、3、4）在特定情况下可共存
  2. 安装Wgcf-WARP:虚拟IPV4
  3. 安装Wgcf-WARP:虚拟IPV6
  4. 安装Wgcf-WARP:虚拟IPV4+IPV6
  5. 安装Socks5-WARP：IPV4本地Socks5代理
 -------------------------------------------------------------------------------------------
  6. WARP账户升级：WARP+账户与WARP+Teams账户，一键screen无限刷流量
  7. WARPR解锁NF奈飞：自动识别WARP配置环境，一键screen刷奈飞IP
  8. WARP开启、停止、卸载
  0. 退出脚本 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 VPS系统信息如下：
 VPS操作系统: CentOS Linux 7 (Core)  内核版本: 5.10.89  CPU架构 : AMD64  虚拟化类型: kvm  TCP算法: bbrplus
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
 当前VPS IPV4接管出站流量情况如下 
 IPV4 WARP状态：关闭中
 [ HOSTODO服务商 ]获取IPV4：116.127.6.151
 IPV4 奈飞NF解锁情况：恭喜呀，当前IP可解锁奈飞Netflix流媒体...   IPV4 所在地区：美国（United States）
------------------------------------------------------------------------------------------------
 当前VPS IPV6接管出站流量情况如下
 IPV6 WARP状态：关闭中
 [ HOSTODO服务商 ]获取IPV6：2606:45d0:30:46::af3d
 IPV6 奈飞NF解锁情况：恭喜呀，当前IP可解锁奈飞Netflix流媒体...   IPV6 所在地区：美国（United States）
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
 当前Socks5-WARP客户端本地代理127.0.0.1情况如下
 Socks5 WARP状态：未安装Socks5-WARP客户端
------------------------------------------------------------------------------------------------

请输入数字:3
cat: /root/resolv.conf: No such file or directory
[root@hexsen ~]# wget -N https://cdn.jsdelivr.net/gh/kkkyg/CFwarp/CFwarp.sh && bash CFwarp.sh
--2022-01-16 21:27:26--  https://cdn.jsdelivr.net/gh/kkkyg/CFwarp/CFwarp.sh
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... failed: Name or service not known.
wget: unable to resolve host address ‘cdn.jsdelivr.net’
[root@hexsen ~]# `

**Comment by 759071793** [comment]
我知道问题出在哪里了，我需要手动复制一份有dns内容的 resolv.conf 到root 目录下，然后就可以正常使用beta2脚本了。。

**Comment by 759071793** [comment]
刚我手动复制一份 resolv.conf 到 root 目录下就可以运行beta2的234选项了，不过一运行后，我的dns又被清空了，root目录下的resolv.conf被删除了

**Comment by 759071793** [comment]
我将脚本fork 然后删除所有`cat /root/resolv.conf > /etc/resolv.conf`后可以正常使用了。

**Comment by kkkyg** [comment]
> 我将脚本fork 然后删除所有`cat /root/resolv.conf > /etc/resolv.conf`后可以正常使用了。

有这类问题的鸡，原先默认dns是不是都有8.8.8.8？
