### ISSUE TITLE
能否修复whoer.net里面显示真实IP的问题？

### ISSUE THREAD

**Issue by TryTOgte** [kkkyg/CFwarp#24]
就是想着能否修复一下在whoer.net这个网站中显示真实IP的问题？

**Comment by TryTOgte** [comment]
就是VPS添加上warp之后，正常的网站比如showip.net中显示的ip都是warp生成的IP，但是whoer.net这个网站里面检测到的是真实的vps的IP，我记得之前的脚本生成的在这个网站中是显示了一些匿名的IP，不是真实IP，不知道是什么原理？

**Comment by lucas-su-dev** [comment]
好像是因为cloudflare系的都知道你真正的ip是多少，没法隐藏，因为你们用的就是cloudflare warp。。具体还得专业的来解释

**Comment by TryTOgte** [comment]
哦，whoer原来是cloudflare系的，我之前不知道，不过我记得之前用甬哥的warp脚本都是能隐藏的，显示的不是真实IP也不是warp生成的IP，而是233开头的一个不知道提供商的匿名IP

**Comment by kkkyg** [comment]
> 哦，whoer原来是cloudflare系的，我之前不知道，不过我记得之前用甬哥的warp脚本都是能隐藏的，显示的不是真实IP也不是warp生成的IP，而是233开头的一个不知道提供商的匿名IP

Warp接管出站流量！第三方网站测ip只能是warp的ip，除非关了warp

**Comment by TryTOgte** [comment]
恩，好的甬哥，不知道你之前每修改一次的脚本是否有备份？如果有的话能否发一份到我的邮箱里heolan1999N@outlook.com。谢谢
