### ISSUE TITLE
dd安装的debian11报错了，求解决，谢谢：）

### ISSUE THREAD

**Issue by ziyocc** [kkkyg/CFwarp#25]
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100  1688  100  1688    0     0   2046      0 --:--:-- --:--:-- --:--:--  2043
OK
CFwarp.sh: line 440: lsb_release: command not found
deb http://pkg.cloudflareclient.com/  main
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.

**Comment by kkkyg** [comment]
安装socks5？输入lsb_release -sc 有什么提示？
从提示上来看是说无法读取源文件！d后的系统问题

**Comment by ziyocc** [comment]
我哦，勇哥起的真早：）

root@172:~# lsb_release -sc
bullseye

貌似是密匙之类的问题，我是搞不懂的。。。

**Comment by kkkyg** [comment]
> 我哦，勇哥起的真早：）
> 
> root@172:~# lsb_release -sc bullseye
> 
> 貌似是密匙之类的问题，我是搞不懂的。。。

换个d试试
