### ISSUE TITLE
可否指定warp地区？（非刷netflix）

### ISSUE THREAD

**Issue by LonelyJupiter** [kkkyg/CFwarp#26]
甬哥好！

我的新加坡nat小鸡，应该是因为ip的原因，老是分配到美国v4IP（倒是v6的大多数情况下是新加坡的），导致一些cdn的网站会连接美国节点导致延迟超高。。

所以脚本能否自动检测分配的ip地区，如果非新加坡就继续尝试更换ip？

谢谢！

**Comment by kkkyg** [comment]
> 甬哥好！
> 
> 我的新加坡nat小鸡，应该是因为ip的原因，老是分配到美国v4IP（倒是v6的大多数情况下是新加坡的），导致一些cdn的网站会连接美国节点导致延迟超高。。
> 
> 所以脚本能否自动检测分配的ip地区，如果非新加坡就继续尝试更换ip？
> 
> 谢谢！

下个版本加入此功能！

**Comment by kkkyg** [comment]
> 甬哥好！
> 
> 我的新加坡nat小鸡，应该是因为ip的原因，老是分配到美国v4IP（倒是v6的大多数情况下是新加坡的），导致一些cdn的网站会连接美国节点导致延迟超高。。
> 
> 所以脚本能否自动检测分配的ip地区，如果非新加坡就继续尝试更换ip？
> 
> 谢谢！

刚更新BETA 4，已支持。
