### ISSUE TITLE
关于warp+刷流量的问题

### ISSUE THREAD

**Issue by hutianyu2006** [kkkyg/CFwarp#27]
我在screen后台刷流量的时候发现手机上确实收到了1.1.1.1 APP的玩命推送，但是当我实际上点开1.1.1.1 APP的时候，我的warp+流量是0MB，这是什么情况？

**Comment by 2ndMessiah** [comment]
重置安全密钥

**Comment by kkkyg** [comment]
楼上正解！项目说明其实也写明了

**Comment by hutianyu2006** [comment]
啊好吧，我没认真看readme。。。
