### ISSUE TITLE
非 root 用户使用 sudo 运行不能 screen 刷 ip

### ISSUE THREAD

**Issue by realEthanZou** [kkkyg/CFwarp#28]
https://github.com/kkkyg/CFwarp/blob/5eaba7f6333497dde81bbc3bee7551b027a63ec6/CFwarp.sh#L584

check.sh 会被下载到 /home/username/ 下而不是 /root/

**Comment by kkkyg** [comment]
必须root用户

**Comment by realEthanZou** [comment]
前面写错了，是会下载到当前工作目录。如果脚本其他部分不太好改，要求这个组件必须存在于 /root，那考虑下使用 wget -O？

**Comment by kkkyg** [comment]
> 前面写错了，是会下载到当前工作目录。如果脚本其他部分不太好改，要求这个组件必须存在于 /root，那考虑下使用 wget -O？

你是以非ROOT运行？？除了这个问题，别的都运行正常？

**Comment by realEthanZou** [comment]
非 root 用户使用 sudo 运行
其他都正常

**Comment by kkkyg** [comment]
> 非 root 用户使用 sudo 运行 其他都正常

要不放都放在/etc/wireguard下吧？！
