### ISSUE TITLE
有没有办法将Teams设置应用在SOCKS5 WARP Client？

### ISSUE THREAD

**Issue by windfrom** [kkkyg/CFwarp#29]
仅安装了 WARP Linux Client并开启 Socks5 代理模式，想分流nf流量而不想让所有流量都通过WARP代理

有没有办法将Teams设置应用在SOCKS5 WARP Client上？

仅安装WARP客户端的话在/etc/wireguard下没有发现wgcf.conf配置文件，没法应用teams设置？

目前得安装WARP IPv4或IPv6网络接口后才有wgcf.conf配置文件

**Comment by kkkyg** [comment]
Socks5只能刷手机流量的warp+，不支持teams
