### ISSUE TITLE
请问可以对不能升级内核的ovz小鸡支持wg-go安装吗？

### ISSUE THREAD

**Issue by NanoBooster** [kkkyg/CFwarp#31]
内核太旧了，安装wg好像不成功，查了一下似乎只能用wg-go

**Comment by kkkyg** [comment]
脚本支持wg-go的，ovz小鸡开启TUN后就可以安装是，发下你的小鸡系统配置信息

**Comment by NanoBooster** [comment]
系统信息：

 CPU Model          : Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
 CPU Cores          : 1
 CPU Frequency      : 2024.548 MHz
 CPU Cache          : 8192 KB
 Total Disk         : 9.8 GB (1.5 GB Used)
 Total Mem          : 512 MB (112 MB Used)
 Total Swap         : 0 MB (0 MB Used)
 System uptime      : 0 days, 0 hour 28 min
 Load average       : 0.14, 0.07, 0.05
 OS                 : Debian GNU/Linux 10
 Arch               : x86_64 (64 Bit)
 Kernel             : 4.19.0
 TCP CC             :
 Virtualization     : OpenVZ
 Organization       : AS16276 OVH SAS
 Location           : Singapore / SG
 Region             : Singapore

cat: /dev/net/tun: File descriptor in bad state
这说明tun应该已经开启了
可能确实不是wg安装失败的问题，不管是脚本安装还是手动安装wg，报错都跟下面一样。脚本就是提示无法获取warp ip。我卸载了lkl-haproxy的那个bbr也不行。
Feb 10 14:08:41 l.888089.xyz wg-quick[24907]: /dev/fd/63:6:1-117: Error: Could not process rule: No such file or directory
Feb 10 14:08:41 l.888089.xyz wg-quick[24907]: [#] resolvconf -d tun.wgcf -f
Feb 10 14:08:41 l.888089.xyz wg-quick[24907]: Too few arguments.
Feb 10 14:08:41 l.888089.xyz wg-quick[24907]: Too few arguments.
Feb 10 14:08:41 l.888089.xyz wg-quick[24907]: [#] ip -6 rule delete table 51820
Feb 10 14:08:41 l.888089.xyz wg-quick[24907]: [#] ip -6 rule delete table main suppress_prefixlength 0
Feb 10 14:08:41 l.888089.xyz wg-quick[24907]: [#] ip link delete dev wgcf
Feb 10 14:08:41 l.888089.xyz systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Feb 10 14:08:41 l.888089.xyz systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
Feb 10 14:08:41 l.888089.xyz systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.

**Comment by NanoBooster** [comment]
请问还需要哪些信息呢？或者需要我尝试哪些操作？多谢大佬了

**Comment by kkkyg** [comment]
> 请问还需要哪些信息呢？或者需要我尝试哪些操作？多谢大佬了

干净的系统下再安装试试

**Comment by NanoBooster** [comment]
脚本失败后再次进入脚本就检测不到ip地址了，/etc/network/interfaces并没有被修改过，但是/etc/resolv.conf好像不见了所以解析不了DNS。。。加了之后脚本还是成功不了

**Comment by NanoBooster** [comment]
我把debian换成ubuntu试试吧，本小白已经黔驴技穷了，看看大佬还有没有什么思路

**Comment by NanoBooster** [comment]
换了ubuntu好像安装成功了，感谢，我试试看功能是否正常

**Comment by kkkyg** [comment]
> 换了ubuntu好像安装成功了，感谢，我试试看功能是否正常

我一直觉得ubuntu是万金油系统。。。

**Comment by NanoBooster** [comment]
现在可以获取IP地址了，但无法安装socks本地代理，安装过程提示缺少lsb_release，但是我无法下载lsb-core，现在输入apt update报错如下
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.
现在咋办呢

**Comment by kkkyg** [comment]
> 

ubuntu20.04吗?

**Comment by NanoBooster** [comment]
最多只能装到18.04.....

**Comment by kkkyg** [comment]
> 最多只能装到18.04.....

我记得官方写的只支持16与20。。

**Comment by NanoBooster** [comment]
那我再换一次，哈哈哈，谢谢你的耐心解答，等等给你反馈

**Comment by NanoBooster** [comment]
CFwarp.sh: line 381: lsb_release: command not found
deb http://pkg.cloudflareclient.com/  main
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.
换了好像也不行，我提前手动装一下试试吧

**Comment by NanoBooster** [comment]
装了curl screen sudo lsb-core apt-transport-https之后可以正常用了...gullo给的系统可能太精简了点。麻烦大佬了，可以close了

**Comment by kkkyg** [comment]
> 装了curl screen sudo lsb-core apt-transport-https之后可以正常用了...gullo给的系统可能太精简了点。麻烦大佬了，可以close了

发下你另外单独安装的那些完整命令吧！我集成到脚本中去！
