### ISSUE TITLE
由于 cloudflare 更新 warp-cli settings 的输出 Socks5 无法正常使用

### ISSUE THREAD

**Issue by realEthanZou** [kkkyg/CFwarp#32]
https://github.com/kkkyg/CFwarp/blob/f80f422830e702ec99bc6898e7b9b7fc980155ca/CFwarp.sh#L117

现在端口一行为 ```Mode: WarpProxy on port 40000```，现在脚本中的 parsing 无法正常进行，导致无法获取到端口，```$mport``` 无法被后续代码引用

话说既然都是脚本安装，端口不就是固定 40000 了么。自己折腾，自定义端口了的人应该也不会再用这脚本

**Comment by kkkyg** [comment]
感谢提醒！明天修复
