### ISSUE TITLE
亚马逊AWS EC2实例出现断网

### ISSUE THREAD

**Issue by xu-zheng-hao** [kkkyg/CFwarp#33]
在安装完warp的ipv4+ipv6后挂着几个小时后会出现ipv4和ipv6都获取不到ip的情况，我也测试了EC2的香港，日本，澳大利亚，新加坡地区，都会出现这种情况，出现这种状况后服务器内网访问其他网络资源会直接报错，ping，curl超时等希望赶紧修复

**Comment by kkkyg** [comment]
> 在安装完warp的ipv4+ipv6后挂着几个小时后会出现ipv4和ipv6都获取不到ip的情况，我也测试了EC2的香港，日本，澳大利亚，新加坡地区，都会出现这种情况，出现这种状况后服务器内网访问其他网络资源会直接报错，ping，curl超时等希望赶紧修复

发现这问题后
vi /etc/resolv.conf
发下dns有没被恢复？

**Comment by kkkyg** [comment]
出现这问题后
试试wg-quick down wgcf
再wg-quick up wgcf
看下能否恢复

**Comment by 2ndMessiah** [comment]
是不是用了debian。我在debian上经常碰见无缘无故双栈模式下warp ipv4丢失。换成ubuntu之后再也没出现过。fscarmen的issues下面有提到这个问题。目前看起来跟内核关联不是很大。

**Comment by kkkyg** [comment]
> 是不是用了debian。我在debian上经常碰见无缘无故双栈模式下warp ipv4丢失。换成ubuntu之后再也没出现过。fscarmen的issues下面有提到这个问题。目前看起来跟内核关联不是很大。

一直觉得ubuntu容错率最高！

**Comment by xu-zheng-hao** [comment]
> 是不是用了debian。我在debian上经常碰见无缘无故双栈模式下warp ipv4丢失。换成ubuntu之后再也没出现过。fscarmen的issues下面有提到这个问题。目前看起来跟内核关联不是很大。
> 
> ps lz的“赶紧修复”说的真轻巧

兄弟，我用的就是ubuntu啊，这东西就很几把离谱

**Comment by xu-zheng-hao** [comment]
> vi /etc/resolv.conf

nameserver 127.0.0.53
options edns0 trust-ad
search ap-southeast-2.compute.internal

**Comment by xu-zheng-hao** [comment]
> 出现这问题后 试试wg-quick down wgcf 再wg-quick up wgcf 看下能否恢复 反馈信息发下

不行，不过卸载重装后我的日本机器就好了，其他的还是几个小时后就断网

**Comment by kkkyg** [comment]
> > vi /etc/resolv.conf
> 
> nameserver 127.0.0.53 options edns0 trust-ad search ap-southeast-2.compute.internal

被强制恢复了！！无奈
