### ISSUE TITLE
非常好的工具，可惜CF越来越多地区刷不出NF了

### ISSUE THREAD

**Issue by lucas-su-dev** [kkkyg/CFwarp#34]
本人有十几个地区的服务器，这个脚本用的很好。
最近两天，香港，台湾，新加坡，日本，都已经刷不出IP，范围在逐渐扩大。
可能是NF封锁的IP越来越多，也可能是刷IP的人越来越多，实在刷不出可解锁的IP了。
以前香港和新加坡就是最难刷出IP的地区，现在已经基本不可用了。只有欧美国家可用的IP还不少。

**Comment by kkkyg** [comment]
感谢支持！这情况也正常！用的人越来越多了
