### ISSUE TITLE
获取warp ip失败

### ISSUE THREAD

**Issue by lucas-su-dev** [kkkyg/CFwarp#35]
昨天未知原因导致2台vps失联，ipv4和ipv6均无，无法连接外网，我直接重装系统了。
今天新vps使用脚本发现无法获取ip，选择选项3- ipv4，ipv6
已确实认识目前最新脚本。

**Comment by kkkyg** [comment]
半夜中断过几小时，现在恢复了。

**Comment by aaronx0607** [comment]
> 昨天未知原因导致2台vps失联，ipv4和ipv6均无，无法连接外网，我直接重装系统了。 今天新vps使用脚本发现无法获取ip，选择选项3- ipv4，ipv6 已确实认识目前最新脚本。

我的情况与你一样，目前VPS也是无法获取IP

**Comment by kkkyg** [comment]
> > 昨天未知原因导致2台vps失联，ipv4和ipv6均无，无法连接外网，我直接重装系统了。 今天新vps使用脚本发现无法获取ip，选择选项3- ipv4，ipv6 已确实认识目前最新脚本。
> 
> 我的情况与你一样，目前VPS也是无法获取IP

现在应该都好了吧！

**Comment by sdfsdfsdf145314364** [comment]
昨天WARP自身爆炸了应该，我也出现了一样的问题，重装才好，今天没问题正常了。

**Comment by kkkyg** [comment]
> 昨天WARP自身爆炸了应该，我也出现了一样的问题，重装才好，今天没问题正常了。 感觉脚本应该需要优化一点，找一下具体是什么原因导致的，如果这样断线的话，选择回自身IP地址就好了，省的重装。

很好的建议！！下次更新就这样搞

**Comment by ingnelson** [comment]
@sdfsdfsdf145314364 @lucas-su-dev @kkkyg it happen to me too. 
I solve it restarting the CFWARP like this : 

systemctl restart wg-quick@wgcf

I would like to know if the owner fix this problem .

**Comment by kkkyg** [comment]
> @sdfsdfsdf145314364 @lucas-su-dev @kkkyg it happen to me too. I solve it restarting the CFWARP like this :
> 
> systemctl restart wg-quick@wgcf
> 
> I would like to know if the owner fix this problem .

The next update will support it

**Comment by bzaiboy** [comment]
依然出现获取warp ip失败

**Comment by kkkyg** [comment]
> 依然出现获取warp ip失败

干净系统下试！什么vps？

**Comment by kkkyg** [comment]
> Debian10，系统重装依然失败 发自我的iPhone
> […](#)
> 在 2022年3月8日，20:46，甬哥kkkyg ***@***.***> 写道： ﻿ 依然出现获取warp ip失败 干净系统下试！什么vps？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

没显示出来。。。

**Comment by lucas-su-dev** [comment]
我HK debian 11新系统也是获取ip失败~

**Comment by kkkyg** [comment]
> 我HK debian 11新系统也是获取ip失败~

试试下非HK的区。

**Comment by lucas-su-dev** [comment]
gcp canada toronto debian 11也失败啦=。=

**Comment by ingnelson** [comment]
@kkkyg when the problem happened . I see the wireguard is active , but the connections it is closed . 
Other thing I see , it is the "lag connection " is 5600 ms.

Maybe it is the handshake ? . This happen every day to me.

**Comment by kkkyg** [comment]
> gcp canada toronto debian 11也失败啦=。=

GCP别的区都这样？

**Comment by kkkyg** [comment]
> @kkkyg when the problem happened . I see the wireguard is active , but the connections it is closed . Other thing I see , it is the "lag connection " is 5600 ms.
> 
> Maybe it is the handshake ? . This happen every day to me.

beta：

wget -N https://raw.githubusercontent.com/kkkyg/1/main/warpauto.sh

run it with SCREEN

**Comment by lucas-su-dev** [comment]
![image](https://user-images.githubusercontent.com/42117215/157570746-925bea3b-06f1-4949-9570-a692265097e5.png)
其他区我没敢试，因为本身是好的，加拿大以前也是好的，重装了就不行了。我用另一个作者的脚本也是一样的情况重试5次失败

**Comment by kkkyg** [comment]
> ![image](https://user-images.githubusercontent.com/42117215/157570949-67598833-e0e2-4cee-93f0-2b590741c595.png) 其他区我没敢试，我估计重装也不行，本身是好的，前两天脚本崩了重装了香港和加拿大的，重装以后都不行了。我用另一个作者的脚本也是一样的情况重试5次失败

那就是cloudflare的问题！等官方慢慢修吧

**Comment by ingnelson** [comment]
@kkkyg i run the script , it shows when the connections is lost , but it does not fix it. 

What do you think if you modify the script and when the script find that connection is lost , it automatically execute the command : systemctl restart wg-quick@wgcf

What do you say ? What would happen ?

![Screenshot_2022-03-11-12-01-42-541_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/157914424-e218a364-6cd4-4d48-afbd-ee49fafe6107.jpg)

**Comment by kkkyg** [comment]
> @kkkyg我运行脚本，它显示连接何时丢失，但它没有修复它。
> 
> 如果你修改脚本，当脚本发现连接丢失时，你会怎么想，它会自动执行命令：systemctl restart wg-quick@wgcf
> 
> 你说什么 ？会发生什么 ？
> 
> ![Screenshot_2022-03-11-12-01-42-541_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/157914424-e218a364-6cd4-4d48-afbd-ee49fafe6107.jpg)

I think…………the WARP of your VPS will fail at least once within 30 seconds, and the WARP failure frequency is very high，Is this how you usually feel?

**Comment by kkkyg** [comment]
> @kkkyg i run the script , it shows when the connections is lost , but it does not fix it.
> 
> What do you think if you modify the script and when the script find that connection is lost , it automatically execute the command : systemctl restart wg-quick@wgcf
> 
> What do you say ? What would happen ?
> 
> ![Screenshot_2022-03-11-12-01-42-541_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/157914424-e218a364-6cd4-4d48-afbd-ee49fafe6107.jpg)



> @kkkyg i run the script , it shows when the connections is lost , but it does not fix it.
> 
> What do you think if you modify the script and when the script find that connection is lost , it automatically execute the command : systemctl restart wg-quick@wgcf
> 
> What do you say ? What would happen ?
> 
> ![Screenshot_2022-03-11-12-01-42-541_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/157914424-e218a364-6cd4-4d48-afbd-ee49fafe6107.jpg)


Updated the script, you can try again
wget -N https://raw.githubusercontent.com/kkkyg/1/main/warpauto.sh

**Comment by a49v033** [comment]
有个建议，如果本地区的IP刷不出来，弹出让用户选择其它区域IP，就像netfilx换IP一样。

**Comment by kkkyg** [comment]
> @kkkyg i run the script , it shows when the connections is lost , but it does not fix it.
> 
> What do you think if you modify the script and when the script find that connection is lost , it automatically execute the command : systemctl restart wg-quick@wgcf
> 
> What do you say ? What would happen ?
> 
> ![Screenshot_2022-03-11-12-01-42-541_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/157914424-e218a364-6cd4-4d48-afbd-ee49fafe6107.jpg)



> Updated the script, you can try again
> wget -N https://raw.githubusercontent.com/kkkyg/1/main/warpauto.sh



> 有个建议，如果本地区的IP刷不出来，弹出让用户选择其它区域IP，就像netfilx换IP一样。

不设置区域就是自动全球区域就近原则。。。当前默认就是你说的。。不过区域选择本身就很不现实，如果你平时看到刷出的WARP的IP在某些区域有出现，那还可以设置，如果没出现过某些地区，而你硬要选择某些区域，那就是无限死循环了，刷不出结果。。

**Comment by a49v033** [comment]
现在是在安装的阶段，刷不出IP脚本就自动退出了，装不上去，如果在安装的时候可以手动设置区域，这个问题应该就能解决了。

**Comment by a49v033** [comment]
还是重试5次，如果没有可用IP，再选择其它区域，再试5次。这样是不是更好啊？

**Comment by kkkyg** [comment]
> 还是重试5次，如果没有可用IP，再选择其它区域，再试5次。这样是不是更好啊？

不设置区域是最开放，获取warp IP最快最容易的方式，你可以想想，这如果刷5次都刷不出IP，那就是CF官方或者WARP安装失败的自身问题了。。

**Comment by a49v033** [comment]
可以做两个版本，一个针对现在香港区域的warp刷不出IP的问题，另一个就能通用版本，这样就不会互相有影响，不知可行否？

**Comment by kkkyg** [comment]
> 可以做两个版本，一个针对现在香港区域的warp刷不出IP的问题，另一个就能通用版本，这样就不会互相有影响，不知可行否？

目前warp的香港区一直是off状态，是CF官方问题。。https://www.cloudflarestatus.com/  找到Hong Kong - (HKG)

**Comment by kkkyg** [comment]
> 可以做两个版本，一个针对现在香港区域的warp刷不出IP的问题，另一个就能通用版本，这样就不会互相有影响，不知可行否？

我现在理解你的意思了，你是香港的鸡，100%香港的WARP，现在无法获取。。。。换别的区。。平时有看到过刷到别的地区过吗？

**Comment by a49v033** [comment]
新加坡可以

**Comment by kkkyg** [comment]
> 新加坡可以

大概说下你的鸡平时刷WARP。出现香港与新加坡或者别的区域的比例

**Comment by a49v033** [comment]
之前大部分是香港，因为靠近大陆速度比较快，现在没有了，只能退而求其次新加坡，速度还可以。

**Comment by kkkyg** [comment]
> 之前大部分是香港，因为靠近大陆速度比较快，现在没有了，只能退而求其次新加坡，速度还可以。

现在就没一次刷出WARP新加坡过？全是5次失败？

**Comment by a49v033** [comment]
一键脚本装不了，现在是香港的鸡，连CF warp都装不上，因为安装时刷不出IP，脚本自动退出，装不上。

**Comment by kkkyg** [comment]
> 一键脚本装不了，现在是香港的鸡，连CF warp都装不上，因为安装时刷不出IP，脚本自动退出，装不上。

私聊https://t.me/kkkygkkk

**Comment by ingnelson** [comment]
I just want to say the new update works great 👍. Thank you . I use it every day. Very helpful.

**Comment by kkkyg** [comment]
> 

Ok
