### ISSUE TITLE
CFwarp get stuck

### ISSUE THREAD

**Issue by ingnelson** [kkkyg/CFwarp#36]
Hello 
Sometime the CFwarp get stuck and i have to restart it manually.

When it get stuck , the vps block all the connections . All my program like v2ray or von does not works. 

Is there a way the CFwarp could restart automatically , please ?

**Comment by sdfsdfsdf145314364** [comment]
定時任務。或自主完善一個判斷腳本。

**Comment by kkkyg** [comment]
Next time I update the script, I will support the function of timing detection of warp status

**Comment by kkkyg** [comment]
> 定時任務。或自主完善一個判斷腳本。

下次更新会集成！大家可自定义时间段
