### ISSUE TITLE
希望能加一个刷指定IP段的功能。【已增加此功能】

### ISSUE THREAD

**Issue by sdfsdfsdf145314364** [kkkyg/CFwarp#37]
因为发现有的IP段，进行某些服务的时候延时会低很多，如果有指定IP段的功能，很实用哦。

**Comment by kkkyg** [comment]
感觉都差不多呀。举个例子看

**Comment by sdfsdfsdf145314364** [comment]
> 感覺都差不多呀。舉個例子看

比如我用香港的机器搭建ss，非原生IP，无法玩台服英雄联盟，用了WARP，就可以进入玩，然后特定IP段延迟低一些。

**Comment by kkkyg** [comment]
> 

你指指定地区的ip是吧？

**Comment by sdfsdfsdf145314364** [comment]
> > 
> 
> 你指指定地區的ip是吧？

不，您沒看錯也沒聽錯也沒理解錯，就是IP段，不是指定地區的IP，warp就近分配IP，但是一般一個地區都會有幾個段，多刷幾次一般就能刷到了。

**Comment by kkkyg** [comment]
> > > 
> > 
> > 
> > 你指指定地區的ip是吧？
> 
> 不，您沒看錯也沒聽錯也沒理解錯，就是IP段，不是指定地區的IP，warp就近分配IP，但是一般一個地區都會有幾個段，多刷幾次一般就能刷到了。

比如你想要8.24.25.26这个段的ip，确定的段是8.24.25？

**Comment by sdfsdfsdf145314364** [comment]
> > > > 
> > > 
> > > 
> > > 你指指定地區的ip是吧？
> > 
> > 
> > 不，您沒看錯也沒聽錯也沒理解錯，就是IP段，不是指定地區的IP，warp就近分配IP，但是一般一個地區都會有幾個段，多刷幾次一般就能刷到了。
> 
> 比如你想要8.24.25.26这个段的ip，确定的段是8.24.25？

對的。

**Comment by kkkyg** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你指指定地區的ip是吧？
> > > 
> > > 
> > > 不，您沒看錯也沒聽錯也沒理解錯，就是IP段，不是指定地區的IP，warp就近分配IP，但是一般一個地區都會有幾個段，多刷幾次一般就能刷到了。
> > 
> > 
> > 比如你想要8.24.25.26这个段的ip，确定的段是8.24.25？
> 
> 對的。

那就是自定义24.25了。。看来你对比得很仔细。。。我到时看看

**Comment by kkkyg** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你指指定地區的ip是吧？
> > > 
> > > 
> > > 不，您沒看錯也沒聽錯也沒理解錯，就是IP段，不是指定地區的IP，warp就近分配IP，但是一般一個地區都會有幾個段，多刷幾次一般就能刷到了。
> > 
> > 
> > 比如你想要8.24.25.26这个段的ip，确定的段是8.24.25？
> 
> 對的。
已更新
![7709c19613d80573098147166fd033e](https://user-images.githubusercontent.com/90416692/158313177-953e502e-6bcf-4085-bbfd-bd400c972efb.png)

**Comment by sdfsdfsdf145314364** [comment]
好像有BUG，IP是需要的目標段，但是也會一直切換IP。

**Comment by sdfsdfsdf145314364** [comment]
> 測試有BUG。
> 
> 接口好像是有刷新的限制，查詢的IP返回容易＝“”

最好大家刷IP的時候時間設置的間隙大一點，或者多增加幾個接口。

**Comment by kkkyg** [comment]
> > 測試有BUG。
> > 接口好像是有刷新的限制，查詢的IP返回容易＝“”
> 
> 最好大家刷IP的時候時間設置的間隙大一點，或者多增加幾個接口。

甬哥的刷ip功能都可自定义间隔！！！你指的接口是？

**Comment by sdfsdfsdf145314364** [comment]
> > > 測試有BUG。
> > > 接口好像是有刷新的限制，查詢的IP返回容易＝“”
> > 
> > 
> > 最好大家刷IP的時候時間設置的間隙大一點，或者多增加幾個接口。
> 
> 甬哥的刷ip功能都可自定义间隔！！！你指的接口是？

恩，這不算是bug，就是IP查詢接口，設置時間間隔在1分鐘左右就沒問題，如果設置查詢本機IP的間隔特別短，可能會返回空。

**Comment by kkkyg** [comment]
> > > > 測試有BUG。
> > > > 接口好像是有刷新的限制，查詢的IP返回容易＝“”
> > > 
> > > 
> > > 最好大家刷IP的時候時間設置的間隙大一點，或者多增加幾個接口。
> > 
> > 
> > 甬哥的刷ip功能都可自定义间隔！！！你指的接口是？
> 
> 恩，這不算是bug，就是本機IP查詢接口，設置時間間隔在1分鐘左右就沒問題，如果設置查詢本機IP的間隔特別短，可能會返回空。

是的！可以理解为太频繁反应不过来！哈哈
