### ISSUE TITLE
Bug回报:现在的脚本需要刷所在地区的ip功能失效,不显示任何国家,疑似ip.sb的api问题

### ISSUE THREAD

**Issue by sosomoo** [kkkyg/CFwarp#40]
如题

**Comment by kkkyg** [comment]
> 如题

重新用脚本运行下试试，再发图！这个问题前几天应该已修复的了

**Comment by sosomoo** [comment]
<img width="868" alt="CleanShot 2022-04-01 at 17 56 30@2x" src="https://user-images.githubusercontent.com/47846341/161241265-969ba9f3-d37d-495d-8d88-2d2a2f95212c.png">

**Comment by sosomoo** [comment]
就是这样,永远会显示这个,其实已经是新加坡的CFIP了

**Comment by sosomoo** [comment]
<img width="970" alt="CleanShot 2022-04-01 at 17 58 16@2x" src="https://user-images.githubusercontent.com/47846341/161241517-d3747329-2627-468b-a3b9-aad14f13e18a.png">

**Comment by kkkyg** [comment]
> <img alt="CleanShot 2022-04-01 at 17 58 16@2x" width="970" src="https://user-images.githubusercontent.com/47846341/161241517-d3747329-2627-468b-a3b9-aad14f13e18a.png">

不好意思！我都忘了！现已修复

**Comment by kkkyg** [comment]
> > > <img alt="CleanShot 2022-04-01 at 17 58 16@2x" width="970" src="https://user-images.githubusercontent.com/47846341/161241517-d3747329-2627-468b-a3b9-aad14f13e18a.png">
> > 
> > 
> > 不好意思！我都忘了！现已修复！重新运行设置下就可以了！很好奇！你是什么vps什么地区的？居然会用到这个很少人用的功能！
> 
> 新加坡的,有时候会跳到美国去,刚才测试了一下,已经正常了,非常感谢提供这么好的脚本

Ok

**Comment by kkkyg** [comment]
> > > > <img alt="CleanShot 2022-04-01 at 17 58 16@2x" width="970" src="https://user-images.githubusercontent.com/47846341/161241517-d3747329-2627-468b-a3b9-aad14f13e18a.png">
> > > 
> > > 
> > > 不好意思！我都忘了！现已修复！重新运行设置下就可以了！很好奇！你是什么vps什么地区的？居然会用到这个很少人用的功能！
> > 
> > 
> > 新加坡的,有时候会跳到美国去,刚才测试了一下,已经正常了,非常感谢提供这么好的脚本
> 
> Ok，能帮到你就好！此功能的确为这种情况而生！

**Comment by sosomoo** [comment]
<img width="1200" alt="CleanShot 2022-04-10 at 11 22 08@2x" src="https://user-images.githubusercontent.com/47846341/162600124-f3c7fa53-1dbb-492f-b77c-26d4280e2692.png">
大佬你好,又开始出现这样的情况了

**Comment by kkkyg** [comment]
> <img alt="CleanShot 2022-04-10 at 11 22 08@2x" width="1200" src="https://user-images.githubusercontent.com/47846341/162600124-f3c7fa53-1dbb-492f-b77c-26d4280e2692.png">
> 
> 大佬你好,又开始出现这样的情况了

现在还是这样吗？

**Comment by sosomoo** [comment]
> > <img alt="CleanShot 2022-04-10 at 11 22 08@2x" width="1200" src="https://user-images.githubusercontent.com/47846341/162600124-f3c7fa53-1dbb-492f-b77c-26d4280e2692.png">
> > 大佬你好,又开始出现这样的情况了
> 
> 现在还是这样吗？

已经正常了,非常感谢,感觉这个应该是 ip.sb的api 问题

**Comment by sosomoo** [comment]
> > > <img alt="CleanShot 2022-04-10 at 11 22 08@2x" width="1200" src="https://user-images.githubusercontent.com/47846341/162600124-f3c7fa53-1dbb-492f-b77c-26d4280e2692.png">
> > > 大佬你好,又开始出现这样的情况了
> > 
> > 
> > 现在还是这样吗？
> 
> 已经正常了,非常感谢,感觉这个应该是 ip.sb的api 问题

但是很奇怪,用CFwarp.sh这个脚本的时候,是能正常看到所属国家的

**Comment by kkkyg** [comment]
> > > > <img alt="CleanShot 2022-04-10 at 11 22 08@2x" width="1200" src="https://user-images.githubusercontent.com/47846341/162600124-f3c7fa53-1dbb-492f-b77c-26d4280e2692.png">
> > > > 大佬你好,又开始出现这样的情况了
> > > 
> > > 
> > > 现在还是这样吗？
> > 
> > 
> > 已经正常了,非常感谢,感觉这个应该是 ip.sb的api 问题
> 
> 但是很奇怪,用CFwarp.sh这个脚本的时候,是能正常看到所属国家的

检测间隔时间设置得不要太短啦！！
